version: "2.3"
services:
  evolidb:
    restart: always
    env_file: ./.env
    container_name: evolidb
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - evoli-network

  app:
    depends_on:
      - evolidb
    container_name: evoli-web-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    networks: ['evoli-network']
  

networks:
  evoli-network:
    driver: bridge

volumes:
  db: