services:
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    container_name: evoli-db
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
      - ./dump.sql:/docker-entrypoint-initdb.d/
  app:
    depends_on:
      - mysqldb
    container_name: evoli-web-app
    build:
      context: .
      dockerfile: Dockerfile
    image: node-mysql-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8084:80
      environment:
        - PMA_ARBITRARY=1
volumes: 
  db:
  db-config: